implemented ai ranking of moves
maxmmyron/twentyfortygreat pull request #12
Opened 2023-05-25 20:58 UTC by tadhgj

may consider using different ai but tbd

2023-05-25 21:56 UTC, maxmmyron requested changes
Only one change necessary; if you want you could also remove the commented out lines but up to you.

Implementation is 🔥

2023-05-25 21:56 UTC, maxmmyron commented on js/ai.js
> +	for (var i = 0; i < 4; i++) {
can we use `let` or `const` :trollface:

2023-05-26 13:12 UTC, tadhgj commented on js/ai.js
> +	for (var i = 0; i < 4; i++) {
> can we use `let` or `const` :trollface:

:|

2023-05-26 13:14 UTC, tadhgj commented
<img width="486" alt="image" src="https://github.com/maxmmyron/twentyfortygreat/assets/17763198/d595898f-c4cb-4213-b550-9cc159d33d1b">

2023-05-27 19:15 UTC, merged